#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Parse command line arguments
USE_PETSC=true
USE_AMGX=false

for arg in "$@"; do
    case $arg in
        USE_AMGX)
            USE_AMGX=true
            USE_PETSC=false
            ;;
        USE_PETSC)
            USE_AMGX=false
            USE_PETSC=true
            ;;
    esac
done

# Copy appropriate fvSolution file
if [ "$USE_PETSC" = true ]; then
    echo "Using PETSC solver configuration"
    if [ -f system/fvSolutionPETSC ]; then
        cp -f system/fvSolutionPETSC system/fvSolution
    else
        echo "Error: fvSolutionPETSC not found in system!"
        exit 1
    fi
else
    echo "Using AMGX solver configuration (default)"
    if [ -f system/fvSolutionAMGX ]; then
        cp -f system/fvSolutionAMGX system/fvSolution
    else
        echo "Error: fvSolutionAMGX not found in system!"
        exit 1
    fi
fi

restore0Dir

runApplication blockMesh

runApplication decomposePar

# runApplication $(getApplication)

# runApplication $(getApplication) -pool fixedSizeMemoryPool -poolSize 10.0

# runParallel $(getApplication) -pool fixedSizeMemoryPool -poolSize 11.0

runParallel $(getApplication)

# runApplication reconstructPar

# postProcess -func writeCellCentres

#------------------------------------------------------------------------------