#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication $(getApplication)

# runApplication $(getApplication) -pool fixedSizeMemoryPool -poolSize 1.0

# postProcess -func writeCellCentres

#------------------------------------------------------------------------------
