#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

# runApplication decomposePar

runApplication $(getApplication)

# runApplication $(getApplication) -pool fixedSizeMemoryPool -poolSize 10.0

# runParallel $(getApplication) -pool fixedSizeMemoryPool -poolSize 11.0

# runParallel $(getApplication)

# runApplication reconstructPar

# postProcess -func writeCellCentres

#------------------------------------------------------------------------------
